# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    docker-compose.yml                                 :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: soum <soum@student.42seoul.kr>             +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2022/11/26 13:45:43 by soum              #+#    #+#              #
#    Updated: 2022/12/28 12:30:43 by soum             ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

version: '3'

services:
  valgrind:
    image: valgrind
    container_name: valgrind
    build:
      context: ./valgrind
    volumes:
      - ${HOME}/workspace:/workspace
